const Restaurante = require('./modeloRestaurante');

const modelo = {}

modelo.documentos = [
    new Restaurante('restaurante_00001' ,'Mc Donald\'s', 'Lider en segmento de restaurante de servicio rapido. Se destaca por sus hamburguesas, papas fritas y sandwiches.','Av. Francisco de Orellana', '(04)293-4321', 'mcdonalds.com.ec', 'https://logodownload.org/wp-content/uploads/2014/04/McDonalds-logo-2.png', 'https://www.arcosdorados.com/wp-content/uploads/2020/10/Espacio-al-Aire-Libre-McDonalds_CCI-scaled.jpg', '10 km de aqui', '630'),
    new Restaurante('restaurante_00002' ,'Eddy\'s BBQ', 'Restaurante especializado en la preparacion de alitas de muchos sabores','Av. Victor Emilio Estrada', '(04)293-5439', 'eddysbbq.com', 'https://scontent.fuio1-1.fna.fbcdn.net/v/t1.6435-9/45029972_2234885583455258_1570056412090859520_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=973b4a&_nc_ohc=bIm9BExfTbkAX9f_LE3&_nc_ht=scontent.fuio1-1.fna&oh=7664954a07addf683e7405e6da473566&oe=615BF035', 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AALk1q8.img?h=0&w=600&m=6&q=60&u=t&o=f&l=f', '23 km de aqui', '250'),
    new Restaurante('restaurante_00003' ,'Burger King', 'Nuestros restaurantes son reconocidos por servir productos de alta calidad, gran sabor, hamburguesas 100% hechas a la parrilla y a un precio accesible.','Urdesa', '(04) 288-8863', 'burgerkingec.com/', 'https://logos-marcas.com/wp-content/uploads/2020/08/Burger-King-Logotipo-1999-presente.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSCwEEK3rbQomatNSii7eKbpIG8OOWN07RPTnrADVaWiCeoHc25ZwyriZhRmr9P2S1ypE&usqp=CAU', '5 km de aqui', '543'),
    new Restaurante('restaurante_00004' ,'Cafe de Tere', 'Restaurante especializado en la preparacion de gran variedad de desayunos, desde bolones hasta tigrillos.','La Garzota', '(04) 262-7348', 'www.elcafedetere.com', 'https://drducto.com/images/clientes/clientes-dr-ducto-02.png', 'https://media-cdn.tripadvisor.com/media/photo-s/11/f8/ce/42/nuestros-tres-tipos-de.jpg', '11 km de aqui', '450'),
    new Restaurante('restaurante_00005' ,'Naturissimo', 'Es la cadena de locales de comida rápida natural (fast good) más grande del país. Dedica su servicio a seleccionar las mejores frutas e ingredientes 100% naturales, para servirlos frescos y recién preparados.','Alborada 4ta Etapa', '(04) 500-0166', 'naturissimo.com', 'http://www.malldelrio.com/administrador/_lib/file/imgmarcas/naturissimo.jpg', 'https://media-cdn.tripadvisor.com/media/photo-p/0e/4b/da/10/yogurt-y-pan-de-yuca.jpg', '6 km de aqui', '300'),
    new Restaurante('restaurante_00006' ,'Pizza Alta', 'En PizzaAlta nos preocupamos por cada detalle, los mejores ingredientes se mezclan para ofrecerte el mejor sabor de la pizza artesanal, con nuestra salsa di pomodoro para que te deleites con cada una de nuestras pizzas, ¿Qué esperas para probarlas?',' C. Primera 600,', '((04) 601-4579', 'http://pizzaalta.com', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxMBZPjB-e5D76GJK1yMeyjubX_qGx6dB8My6CVyQvB9nsKpKkNfRh0E4Z113e6CpUBlI&usqp=CAU', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMUWrVgxkKUvqNKR-v6Gebjx3g665z6mDa9vT9j0aGG9i7yM5A1L3I_dypRP3Qo4MOM5c&usqp=CAU', '12 km de aqui', '100'),
    new Restaurante('restaurante_00007' ,'Noe Sushi', 'Noe Sushi Bar, fusiona de manera extraordinaria la tradicional gastronomía japonesa con el paladar ecuatoriano.','San Marino Shopping', '(04)432-5433', 'www.noesushibar.com/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7YZpg1SCoJXgdhgOLG5TpUa60XADkALzcSmfTBz4oKv8IayzRNG0SyOYr56tkbP-79x8&usqp=CAU', 'https://media-cdn.tripadvisor.com/media/photo-s/02/ec/61/d2/noe.jpg', '12 km de aqui', '150'),
    new Restaurante('restaurante_00008' ,'Riviera Resturant', 'Ofrecemos un servicio atento y amable acompañado de un ambiente tranquilo y relajante al puro estilo italiano. Nuestras especialidades además de las pastas, son los mariscos. Ofrecemos también varios platos de carnes acompañadas de pastas frescas; risotti y una variada selección de platos para vegetarianos.','Av. Victor Emilio Estrada', '098 472 6340', 'rivieraecuador.com', 'https://lh3.googleusercontent.com/proxy/Mw2TCRTcD0fLOEroOZapFGbKJDzEqLDo2-6A07ae5ckZhv1lBDPlqP3IFCjSl5qvVfN7ijHn8EsbzDZt2GvifAVefYMSwpuiaepO5iTMgXis_FjBiaQK5JEr91y0inQRvSDZ51g1WF4', 'https://imagenes.expreso.ec/files/image_800_600/uploads/2020/11/27/5fc1b4ee950ac.jpeg', '23 km de aqui', '250'),
];

module.exports = modelo; 

